import {
  // Income-related icons
  BriefcaseBusiness,
  Laptop,
  TrendingUp,
  Gift,
  CircleDollarSign,
  Building2,
  Coins,
  PiggyBank,
  Wallet,
  DollarSign,
  CreditCard,
  BadgeDollarSign,
  BarChart4,
  CandlestickChart,
  Banknote,
  Receipt,
  HandCoins,
  Landmark,

  // Expense-related icons
  ShoppingBag,
  ShoppingCart,
  Utensils,
  UtensilsCrossed,
  Car,
  Bus,
  Train,
  Plane,
  House,
  Building,
  Home,
  Fuel,
  Hotel,
  Sprout,
  ShoppingBasket,
  Wine,
  Baby,
  Umbrella,
  HeartPulse,
  Stethoscope,
  FirstAid,
  GraduationCap,
  BookOpen,
  Bike,
  Smartphone,
  Monitor,
  Tv,
  Gamepad2,
  Film,
  Music2,
  PartyPopper,
  Cigarette,
  Coffee,
  Pizza,
  Shirt,
  Scissors,
  Dog,
  Cat,
  LibraryBig,
  Wrench,
  Dumbbell,
  Ticket,
  PersonStanding,
  Bill,
  Lightbulb,
  Flame,
  Droplets,
  Wifi,
  PhoneCall,
  Satellite,
  BellRing,
  PaintBucket,
  CloudSun,
  CalendarClock,
  PackageOpen,
  Brush,
  ScrollText,
  SendToBack,
  Clock
} from 'lucide-react';

const Icon = ({searchIcon})=>{
    const icons = [
    // Income Categories
    { name: 'BriefcaseBusiness', component: <BriefcaseBusiness size={24} />, category: 'income' },
    { name: 'Laptop', component: <Laptop size={24} />, category: 'income' },
    { name: 'TrendingUp', component: <TrendingUp size={24} />, category: 'income' },
    { name: 'Gift', component: <Gift size={24} />, category: 'income' },
    { name: 'CircleDollarSign', component: <CircleDollarSign size={24} />, category: 'income' },
    { name: 'Building2', component: <Building2 size={24} />, category: 'income' },
    { name: 'Coins', component: <Coins size={24} />, category: 'income' },
    { name: 'PiggyBank', component: <PiggyBank size={24} />, category: 'income' },
    { name: 'Wallet', component: <Wallet size={24} />, category: 'income' },
    { name: 'DollarSign', component: <DollarSign size={24} />, category: 'income' },
    { name: 'CreditCard', component: <CreditCard size={24} />, category: 'income' },
    { name: 'BadgeDollarSign', component: <BadgeDollarSign size={24} />, category: 'income' },
    { name: 'BarChart4', component: <BarChart4 size={24} />, category: 'income' },
    { name: 'CandlestickChart', component: <CandlestickChart size={24} />, category: 'income' },
    { name: 'Banknote', component: <Banknote size={24} />, category: 'income' },
    { name: 'Receipt', component: <Receipt size={24} />, category: 'income' },
    { name: 'HandCoins', component: <HandCoins size={24} />, category: 'income' },
    { name: 'Landmark', component: <Landmark size={24} />, category: 'income' },
    
    // Expense Categories
    { name: 'ShoppingBag', component: <ShoppingBag size={24} />, category: 'expense' },
    { name: 'ShoppingCart', component: <ShoppingCart size={24} />, category: 'expense' },
    { name: 'Utensils', component: <Utensils size={24} />, category: 'expense' },
    { name: 'UtensilsCrossed', component: <UtensilsCrossed size={24} />, category: 'expense' },
    { name: 'Car', component: <Car size={24} />, category: 'expense' },
    { name: 'Bus', component: <Bus size={24} />, category: 'expense' },
    { name: 'Train', component: <Train size={24} />, category: 'expense' },
    { name: 'Plane', component: <Plane size={24} />, category: 'expense' },
    { name: 'House', component: <House size={24} />, category: 'expense' },
    { name: 'Building', component: <Building size={24} />, category: 'expense' },
    { name: 'Home', component: <Home size={24} />, category: 'expense' },
    { name: 'Fuel', component: <Fuel size={24} />, category: 'expense' },
    { name: 'Hotel', component: <Hotel size={24} />, category: 'expense' },
    { name: 'Sprout', component: <Sprout size={24} />, category: 'expense' },
    { name: 'ShoppingBasket', component: <ShoppingBasket size={24} />, category: 'expense' },
    { name: 'Wine', component: <Wine size={24} />, category: 'expense' },
    { name: 'Baby', component: <Baby size={24} />, category: 'expense' },
    { name: 'Umbrella', component: <Umbrella size={24} />, category: 'expense' },
    { name: 'HeartPulse', component: <HeartPulse size={24} />, category: 'expense' },
    { name: 'Stethoscope', component: <Stethoscope size={24} />, category: 'expense' },
    { name: 'FirstAid', component: <FirstAid size={24} />, category: 'expense' },
    { name: 'GraduationCap', component: <GraduationCap size={24} />, category: 'expense' },
    { name: 'BookOpen', component: <BookOpen size={24} />, category: 'expense' },
    { name: 'Bike', component: <Bike size={24} />, category: 'expense' },
    { name: 'Smartphone', component: <Smartphone size={24} />, category: 'expense' },
    { name: 'Monitor', component: <Monitor size={24} />, category: 'expense' },
    { name: 'Tv', component: <Tv size={24} />, category: 'expense' },
    { name: 'Gamepad2', component: <Gamepad2 size={24} />, category: 'expense' },
    { name: 'Film', component: <Film size={24} />, category: 'expense' },
    { name: 'Music2', component: <Music2 size={24} />, category: 'expense' },
    { name: 'PartyPopper', component: <PartyPopper size={24} />, category: 'expense' },
    { name: 'Cigarette', component: <Cigarette size={24} />, category: 'expense' },
    { name: 'Coffee', component: <Coffee size={24} />, category: 'expense' },
    { name: 'Pizza', component: <Pizza size={24} />, category: 'expense' },
    { name: 'Shirt', component: <Shirt size={24} />, category: 'expense' },
    { name: 'Scissors', component: <Scissors size={24} />, category: 'expense' },
    { name: 'Dog', component: <Dog size={24} />, category: 'expense' },
    { name: 'Cat', component: <Cat size={24} />, category: 'expense' },
    { name: 'LibraryBig', component: <LibraryBig size={24} />, category: 'expense' },
    { name: 'Wrench', component: <Wrench size={24} />, category: 'expense' },
    { name: 'Dumbbell', component: <Dumbbell size={24} />, category: 'expense' },
    { name: 'Ticket', component: <Ticket size={24} />, category: 'expense' },
    { name: 'PersonStanding', component: <PersonStanding size={24} />, category: 'expense' },
    { name: 'Bill', component: <Bill size={24} />, category: 'expense' },
    { name: 'Lightbulb', component: <Lightbulb size={24} />, category: 'expense' },
    { name: 'Flame', component: <Flame size={24} />, category: 'expense' },
    { name: 'Droplets', component: <Droplets size={24} />, category: 'expense' },
    { name: 'Wifi', component: <Wifi size={24} />, category: 'expense' },
    { name: 'PhoneCall', component: <PhoneCall size={24} />, category: 'expense' },
    { name: 'Satellite', component: <Satellite size={24} />, category: 'expense' },
    { name: 'BellRing', component: <BellRing size={24} />, category: 'expense' },
    { name: 'PaintBucket', component: <PaintBucket size={24} />, category: 'expense' },
    { name: 'CloudSun', component: <CloudSun size={24} />, category: 'expense' },
    { name: 'CalendarClock', component: <CalendarClock size={24} />, category: 'expense' },
    { name: 'PackageOpen', component: <PackageOpen size={24} />, category: 'expense' },
    { name: 'Brush', component: <Brush size={24} />, category: 'expense' },
    { name: 'ScrollText', component: <ScrollText size={24} />, category: 'expense' },
    { name: 'SendToBack', component: <SendToBack size={24} />, category: 'expense' },
    { name: 'Clock', component: <Clock size={24} />, category: 'expense' },
  ];
   const value =   icons.find(
 item => item.name===searchIcon
    )
  return (
       value.component
  )

}